/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.table.DefaultTableModel;
import Formularios.Clientes;

/**
 *
 * @author Ian_l
 */
public class ClienteInsertar extends javax.swing.JFrame {

    /**
     * Creates new form ClienteInsertar
     */
    public String nom, tel, dir;
    public int id;
    
    public ClienteInsertar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFieldTel = new javax.swing.JTextField();
        txtFieldId = new javax.swing.JTextField();
        txtFieldNom = new javax.swing.JTextField();
        txtFieldDir = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Dirección");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 440, 230, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar Cliente");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 710, 130);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Identificador del cliente");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 200, 230, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Nombre completo");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 280, 230, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Telefono");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 360, 230, 40);

        txtFieldTel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtFieldTel.setForeground(new java.awt.Color(102, 102, 102));
        txtFieldTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldTel.setText("10 digitos");
        txtFieldTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldTelMouseClicked(evt);
            }
        });
        txtFieldTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTelActionPerformed(evt);
            }
        });
        jPanel2.add(txtFieldTel);
        txtFieldTel.setBounds(310, 360, 340, 40);

        txtFieldId.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtFieldId.setForeground(new java.awt.Color(102, 102, 102));
        txtFieldId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldId.setText("Identificador (solo numero)");
        txtFieldId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldIdMouseClicked(evt);
            }
        });
        txtFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtFieldId);
        txtFieldId.setBounds(310, 200, 340, 40);

        txtFieldNom.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtFieldNom.setForeground(new java.awt.Color(102, 102, 102));
        txtFieldNom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldNom.setText("nombre(s) - apellido(s)");
        txtFieldNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldNomMouseClicked(evt);
            }
        });
        txtFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNomActionPerformed(evt);
            }
        });
        jPanel2.add(txtFieldNom);
        txtFieldNom.setBounds(310, 280, 340, 40);

        txtFieldDir.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtFieldDir.setForeground(new java.awt.Color(102, 102, 102));
        txtFieldDir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldDir.setText("Calle, numero, Fraccionamiento");
        txtFieldDir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldDirMouseClicked(evt);
            }
        });
        txtFieldDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDirActionPerformed(evt);
            }
        });
        jPanel2.add(txtFieldDir);
        txtFieldDir.setBounds(310, 440, 340, 40);

        btnCancelar.setBackground(new java.awt.Color(246, 246, 246));
        btnCancelar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(200, 580, 110, 40);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(-10, 130, 740, 30);

        btnEnviar.setBackground(new java.awt.Color(246, 246, 246));
        btnEnviar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEnviar.setText("Agregar");
        btnEnviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnviar);
        btnEnviar.setBounds(400, 580, 110, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 60, 710, 660);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 1900, 1040);
        jPanel1.getAccessibleContext().setAccessibleName("");

        setBounds(0, 0, 840, 769);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTelActionPerformed

    private void txtFieldTelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldTelMouseClicked
        
        if("10 digitos".equals(txtFieldTel.getText())){
            txtFieldTel.setText("");
        }
    }//GEN-LAST:event_txtFieldTelMouseClicked

    private void txtFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldIdActionPerformed

    private void txtFieldIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldIdMouseClicked
        if("Identificador (solo numero)".equals(txtFieldId.getText())){
            txtFieldId.setText("");
        }
    }//GEN-LAST:event_txtFieldIdMouseClicked

    private void txtFieldNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNomMouseClicked
        if("nombre(s) - apellido(s)".equals(txtFieldNom.getText())){
            txtFieldNom.setText("");
        }
    }//GEN-LAST:event_txtFieldNomMouseClicked

    private void txtFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNomActionPerformed

    private void txtFieldDirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldDirMouseClicked
        if("Calle, numero, Fraccionamiento".equals(txtFieldDir.getText()))
        {
            txtFieldDir.setText("");
        }
    }//GEN-LAST:event_txtFieldDirMouseClicked

    private void txtFieldDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldDirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteInsertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtFieldDir;
    private javax.swing.JTextField txtFieldId;
    private javax.swing.JTextField txtFieldNom;
    private javax.swing.JTextField txtFieldTel;
    // End of variables declaration//GEN-END:variables
}
